KTB-02-wordFile-creation
funnyphatguy/KotlinTelegramBot pull request #1
Opened 2024-12-04 20:42 UTC by funnyphatguy

2024-12-05 19:21 UTC, dzenonce requested changes

2024-12-05 19:21 UTC, dzenonce commented on src/main/kotlin/FileTxt.kt
> +    wordsFile.createNewFile()
Нам **не нужно** создавать новый файл, только читать его

2024-12-05 19:21 UTC, dzenonce commented on src/main/kotlin/FileTxt.kt
> +    val listOfWorlds = wordsFile.readLines()
Давай воспользуемся `forEachLine {}` - это будет еще и короче.

2024-12-05 20:09 UTC, funnyphatguy commented on src/main/kotlin/FileTxt.kt
> +    wordsFile.createNewFile()
Я просто не понимаю тогда вот что. Я же вручную добавил в файл строки hello привет и т.д., т.е. я перед этим создал этот файл же, то есть его нужно создать, правильно?
И второй вопрос, как мы не создавая файл сможем его прочитать?
Т.е. если удалить сейчас words.txt и убрать wordsFile.createNewFile(), компилятор выкинет FileNotFoundException.

Сорри, если вопрос глупый, но искренне не понимаю.

2024-12-06 07:27 UTC, dzenonce commented on src/main/kotlin/FileTxt.kt
> +    wordsFile.createNewFile()
Мы в первый раз создали файл и записали в него данные, больше пересоздавать его нет необходимости, теперь мы только читаем их него данные
Т.е файл мы все-таки создали, но только один раз, дальше код создания файла нам не нужен

2024-12-06 07:29 UTC, dzenonce approved these changes

2024-12-06 07:29 UTC, dzenonce commented on src/main/kotlin/FileTxt.kt
> +
Довольно много пустых строк получилось, давай будем оставлять не больше одной подряд

2024-12-06 07:29 UTC, dzenonce commented on src/main/kotlin/FileTxt.kt
> +    }
Немного форматирование поехало

2024-12-06 18:00 UTC, merged