KTB-08-user-input
funnyphatguy/KotlinTelegramBot pull request #6
Opened 2024-12-12 17:47 UTC by funnyphatguy

2024-12-12 17:51 UTC, funnyphatguy commented
Пока писал код, проверял его и до того момента, когда я начал прописывать val correctAnswersCountUpdate все работало хорошо, т.е. я запускал викторину и в зависимости от выбора ответа - мне засчитывался правильный или неправильный ответ, все работало как надо.
Сейчас при выборе ответа, даже правильного, программа выдает сообщение, что выбор неправильный.
В режиме дебага val correctAnswerId у меня "-1", но я не понимаю почему это происходит.

Подскажите, пожалуйста, как исправить.

2024-12-13 16:38 UTC, funnyphatguy commented
Сейчас разбираю код, в общем, я неправильно в прошлом таске сделал val questionWords = notLearnedList.shuffled().map { it.translation }.take(4), тут нужно просто { it }

2024-12-15 19:21 UTC, dzenonce requested changes

2024-12-15 19:21 UTC, dzenonce commented on src/main/kotlin/FileTxt.kt
>      val questionWords = notLearnedList.shuffled().map { it.translation }.take(4)
Давай здесь будем мапить полноценный объект слова и уже где нужно получать перевод и оригинал чтобы не дублироваци filter (под капотом идет цикл)

2024-12-15 19:21 UTC, dzenonce commented on src/main/kotlin/FileTxt.kt
>      val notLearnedList = dictionary.filter { it.correctAnswersCount <= 2 }
Можно 2 вынести в константу

2024-12-15 19:21 UTC, dzenonce commented on src/main/kotlin/FileTxt.kt
>      val questionWords = notLearnedList.shuffled().map { it.translation }.take(4)
4 тоже в константу

2024-12-15 19:21 UTC, dzenonce commented on src/main/kotlin/FileTxt.kt
> +    wordsFile.printWriter().use { out ->
Сохранять словарь можно еще так
```
        wordsFile.writeText("")
        for (word in words) {
            wordsFile.appendText("${word.original}|${word.translate}|${word.correctAnswersCount}\n")
        }
```

2024-12-15 19:21 UTC, dzenonce requested changes

2024-12-15 19:21 UTC, dzenonce commented on src/main/kotlin/FileTxt.kt
> +                when (userAnswerInput) {
Давай немного изменим подход, что нужно сделать:

1. Слова должны изучаться в бесконечном цикле (вне зависимости от правильности ответа, продолжать изучение слов)
2. Давай получать количество слов и формировать в соответствующем пункте меню т.е это нужно делать только когда пользователь зашел в меню изучения слов:
```
    val notLearnedList = dictionary.filter { it.correctAnswersCount <= 2 }
    val questionWords = notLearnedList.shuffled().map { it }.take(4)
    val correctAnswer = notLearnedList.random()
```
Также с статистикой
Выносим в пункт с статистикой:
```
    val totalCount = dictionary.size
    val learnedCount = dictionary.filter { it.correctAnswersCount >= 3 }.run { size }
    val percent = (learnedCount.toDouble() / totalCount.toDouble() * 100).toInt()
```
3. Меню формировать лучше так:
```
                        val variants = question.variants
                            .mapIndexed { index: Int, word: Word -> " ${index + 1} – ${word.translate}" }
                            .joinToString(
                                separator = "\n",
                                prefix = "\n${question.correctAnswer.original}\n",
                                postfix = "\n ----------\n 0 - Меню",
                            )
                        println(variants)
```
4. Проверять слова можно таким образом:
```
                        val correctAnswerId = question.variants.indexOf(question.correctAnswer)
                        if (userAnswerInput?.minus(1) == correctAnswerId) {
                            println("Правильно!")
                            question.correctAnswer.correctAnswersCount++
                            saveDictionary(dictionary)
                        } else {
                            println("Неправильно! ${question.correctAnswer.original} – это ${question.correctAnswer.translate}")
                            continue
                        }
```

2024-12-16 15:43 UTC, funnyphatguy commented
Спасибо, я поправил, но несколько другим способом, нежели ты писал в коментах.
но у меня не работает запись в файл, хоть ты тресни

2024-12-16 18:10 UTC, dzenonce commented
> Спасибо, я поправил, но несколько другим способом, нежели ты писал в коментах. но у меня не работает запись в файл, хоть ты тресни

По поводу записи в файл тоже оставлял коммент, нужно немного изменить подход и должно заработать

2024-12-17 15:56 UTC, dzenonce requested changes

2024-12-17 15:56 UTC, dzenonce commented on src/main/kotlin/FileTxt.kt
> +            println("${word.original}|${word.translation}|${word.correctAnswersCount}")
А для чего выводить слово каждый раз при сохранении словаря

2024-12-17 15:56 UTC, dzenonce commented on src/main/kotlin/FileTxt.kt
> +                when (val userAnswerInput = readln().toInt()) {
Почему после выбора слова мы выходим в главное меню, изучение должно продолжаться, пока пользователь сам не захочет выйти или не будут выучены все слова

2024-12-17 15:56 UTC, dzenonce commented on src/main/kotlin/FileTxt.kt
> +                        val userAnswerId = questionWords[userAnswerInput - 1].translation
Довольно плохой подход, можно поймать IndexOutOfBound, я вроде бы расписывал примерный алгоритм как это должно выглядеть

2024-12-18 06:05 UTC, funnyphatguy commented on src/main/kotlin/FileTxt.kt
> +            println("${word.original}|${word.translation}|${word.correctAnswersCount}")
Для дебага делал, забыл удалить

2024-12-18 11:50 UTC, funnyphatguy commented
Все, теперь все должно работать.
Я перенес все списки внутрь циклов, чтобы они перемешивались после каждого ответа.
И сам главный список notLearnedList добавил внутрь цикла, чтобы он срабатывал, если слово угадали три и более раз.
Очень тяжело мне далось решение задачи, фрагментарно все вроде понимаю, но заново бы самостоятельно такое не написал бы.

2024-12-18 20:02 UTC, dzenonce approved these changes

2024-12-19 01:24 UTC, merged